# Site settings
title: John W. Cote
email: johnwaynecote+github@gmail.com
url: http://www.johnwaynecote.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6A041C
  secondary: F4A757
  secondary-dark: BB7C36

# Footer settings
footer:
  copyright: Mr. John W. Cote
  # location: Massachusetts, USA
  social: Across the Net
  credits: Proudly made with

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/johnwaynecote
  - title: linkedin
    url: http://linkedin.com/in/johnwcote
  - title: bitbucket
    url: http://bitbucket.org/johncote
  - title: github
    url: http://github.com/johnwcote

# Postal address (add as many lines as necessary)
address:
#  - line: 123 Sesame St.
#  - line: Anytown, 012345

# Credits content

credits: <img class="img-responsive" src="img/github.png" alt="">

# Build settings
markdown: kramdown
permalink: pretty
